/*
* generated by Xtext
*/
package de.dubmas.modulob.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.dubmas.modulob.services.InterfaceDslGrammarAccess;

public class InterfaceDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private InterfaceDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.dubmas.modulob.parser.antlr.internal.InternalInterfaceDslParser createParser(XtextTokenStream stream) {
		return new de.dubmas.modulob.parser.antlr.internal.InternalInterfaceDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "InterfaceModel";
	}
	
	public InterfaceDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(InterfaceDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
