/*
* generated by Xtext
*/
package de.dubmas.modulob.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SystemDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
