/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.dubmas.modulob.system.validation;

import de.dubmas.modulob.Interface;

import de.dubmas.modulob.system.Module;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.dubmas.modulob.system.InterfaceModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InterfaceModelValidator {
	boolean validate();

	boolean validateInterfaces(EList<Interface> value);

	boolean validateModule(Module value);
}
