/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.dubmas.modulob.system.validation;

import de.dubmas.modulob.system.EntityModel;
import de.dubmas.modulob.system.InterfaceModel;
import de.dubmas.modulob.system.NotificationModel;

/**
 * A sample validator interface for {@link de.dubmas.modulob.system.Module}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModuleValidator {
	boolean validate();

	boolean validateInterfaceModel(InterfaceModel value);
	boolean validateEntityModel(EntityModel value);
	boolean validateNotificationModel(NotificationModel value);
}
