/*
 * generated by Xtext
 */
package de.dubmas.modulob;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class InterfaceDslRuntimeModule extends de.dubmas.modulob.AbstractInterfaceDslRuntimeModule {
	
	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return de.dubmas.modulob.InterfaceDslNameProvider.class;
	}
}
