/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.dubmas.modulob.behaviour.validation;

import de.dubmas.modulob.Method;
import de.dubmas.modulob.Notification;

/**
 * A sample validator interface for {@link de.dubmas.modulob.behaviour.Reaction}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReactionValidator {
	boolean validate();

	boolean validateTrigger(Notification value);
	boolean validateReactor(Method value);
	boolean validateOrder(int value);
}
