/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.dubmas.modulob.migration.validation;

import de.dubmas.modulob.Entity;
import de.dubmas.modulob.Feature;

import de.dubmas.modulob.migration.AttributeChange;
import de.dubmas.modulob.migration.RelationChange;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.dubmas.modulob.migration.EntityChange}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EntityChangeValidator {
	boolean validate();

	boolean validateAttributeChanges(EList<AttributeChange> value);
	boolean validateRelationChanges(EList<RelationChange> value);
	boolean validateSourceEntity(Entity value);
	boolean validateDestinationEntity(Entity value);
	boolean validateSourceFeature(Feature value);
	boolean validateDestinationFeature(Feature value);
}
