/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.dubmas.modulob.validation;

import de.dubmas.modulob.ConfigOption;
import de.dubmas.modulob.ConfigValue;

/**
 * A sample validator interface for {@link de.dubmas.modulob.Annotation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AnnotationValidator {
	boolean validate();

	boolean validateOption(ConfigOption value);
	boolean validateValue(ConfigValue value);
}
