/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.dubmas.modulob.validation;

import de.dubmas.modulob.Feature;
import de.dubmas.modulob.ValueObject;

import de.dubmas.modulob.types.TypeRef;

/**
 * A sample validator interface for {@link de.dubmas.modulob.Feature}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FeatureValidator {
	boolean validate();

	boolean validateIsIndexed(boolean value);
	boolean validateIsContainment(boolean value);
	boolean validateName(String value);
	boolean validateInverse(Feature value);
	boolean validateType(TypeRef value);
	boolean validateDefaultValue(ValueObject value);
}
