/*
 * generated by Xtext
 */
package de.dubmas.modulob.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class InterfaceDslUiModule extends de.dubmas.modulob.ui.AbstractInterfaceDslUiModule {
	public InterfaceDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
