/*
* generated by Xtext
*/
package de.dubmas.modulob.common;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.dubmas.modulob.common.ui.internal.DslActivator.getInstance().getInjector("de.dubmas.modulob.common.Dsl");
	}
	
}
